const REQUEST_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  PREPARING: 'preparing',
  DONE: 'done',
  DECLINED: 'declined',
  CANCELLED: 'cancelled'
}

const REQUEST_STATUS_TEXT = {
  [REQUEST_STATUS.PENDING]: '等回应',
  [REQUEST_STATUS.ACCEPTED]: '已安排',
  [REQUEST_STATUS.PREPARING]: '在做了',
  [REQUEST_STATUS.DONE]: '吃过了',
  [REQUEST_STATUS.DECLINED]: '改天吃',
  [REQUEST_STATUS.CANCELLED]: '先不吃'
}

const REQUEST_STATUS_OPTIONS = [
  { value: 'all', label: '全部' },
  { value: REQUEST_STATUS.PENDING, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.PENDING] },
  { value: REQUEST_STATUS.ACCEPTED, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.ACCEPTED] },
  { value: REQUEST_STATUS.PREPARING, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.PREPARING] },
  { value: REQUEST_STATUS.DONE, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.DONE] },
  { value: REQUEST_STATUS.DECLINED, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.DECLINED] },
  { value: REQUEST_STATUS.CANCELLED, label: REQUEST_STATUS_TEXT[REQUEST_STATUS.CANCELLED] }
]

const REQUEST_TRANSITIONS = {
  [REQUEST_STATUS.PENDING]: [
    REQUEST_STATUS.ACCEPTED,
    REQUEST_STATUS.DECLINED,
    REQUEST_STATUS.CANCELLED
  ],
  [REQUEST_STATUS.ACCEPTED]: [REQUEST_STATUS.PREPARING],
  [REQUEST_STATUS.PREPARING]: [REQUEST_STATUS.DONE],
  [REQUEST_STATUS.DONE]: [],
  [REQUEST_STATUS.DECLINED]: [],
  [REQUEST_STATUS.CANCELLED]: []
}

function getRequestStatusText(status) {
  return REQUEST_STATUS_TEXT[status] || '未知状态'
}

function canTransitionRequest(fromStatus, toStatus) {
  return (REQUEST_TRANSITIONS[fromStatus] || []).indexOf(toStatus) >= 0
}

module.exports = {
  REQUEST_STATUS,
  REQUEST_STATUS_TEXT,
  REQUEST_STATUS_OPTIONS,
  REQUEST_TRANSITIONS,
  getRequestStatusText,
  canTransitionRequest
}
